default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    - id: autoflake
      args: [ --in-place, --remove-all-unused-imports, --expand-star-imports, --remove-duplicate-keys, --remove-unused-variables]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: migrations/
        language_version: python3.10
        args: [--line-length=109]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
        args: [--profile, black]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=109, --ignore=E501, --ignore=W291, --ignore=W503]
        language_version: python3.10

exclude: '(migrations|tests|templates|static)/.*'
