version: '3.9.16'

services:
  rabbitmq: 
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
  web:
    volumes:
      - .:/code
      - static:/static
    build: 
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db: 
    image: postgres:14.7
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
  celery:
    restart: always
    build: . 
    command: celery -A config worker -l info
    volumes:
      - .:/code
    container_name: celery
    depends_on:
      - rabbitmq
      - web

volumes:
  postgres_data:
  static:
